### ISSUE TITLE
CI files check is failing

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2023_Analysis_13-super-mare#6]
SHA hashes for CI files do not match the official ones. Please confirm that the CI files (in `.github` directory) are matching those from the CI repository: https://github.com/MATF-Software-Verification/VS-project-ci

**Comment by miljanb99** [comment]
@ivan-ristovic It should be okay now. I've updated the CI support files and compared the SHA hashes locally
